### ISSUE TITLE
[Docs] Error in example for documentation for Creating a Graph

### ISSUE THREAD

**Issue by somelinguist** [CSBiology/FSharp.FGL#29]
**Found a problem with existing documentation?**

The example given in the documentation for Creating a Graph initializes a list of four vertices using List.init, which is 0-based, so the vertices should be 0-3. However, edges are created using vertices 1-4.

https://github.com/CSBiology/FSharp.FGL/blob/3a90c25a25f4a797ad5482f2fbbcf9cd7d398970/docs/content/newgraph.fsx#L26-L33

Running the complete example as is thus produces the following error when creating the graph:

```
System.Exception: Target Vertex 4 does not exist
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at FSharp.FGL.Directed.Edges.add[Vertex,Edge,Label](Vertex _arg1_0, Vertex _arg1_1, Edge _arg1_2, FSharpMap`2 g)
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
Stopped due to error
```
\
Either the vertices should be initialized with `i + 1` or the edges should refer to vertices 0-3.

**Comment by HLWeil** [comment]
Hey

thank you for spotting that!
